### ISSUE TITLE
Cannot download any fragment tsv file in Finaledb

### ISSUE THREAD

**Issue by Kange2014** [epifluidlab/finaledb_portal#3]
Hi, 
I'm sorry to report the issue here because I cannot find the right entry for it. For example, if select to download EE85723/TBR917.rep2 at download page, it just jumps into "https://s3.us-east-2.amazonaws.com/finaledb.epifluidlab.cchmc.org/entries/EE87815/hg19/EE87815.hg19.frag.tsv.bgz" and shows the error of 'accessdenied'.

Can you help fix it kindly?

Thanks.

**Comment by dnaase** [comment]
Sorry about it. We are still moving files to the new server. Please use globus (check document here to start: https://docs.globus.org/how-to/get-started/) endpoint for the temporary solution:
search endpoint: FinaleDB_northwestern_2023
The url for the endpoint is: https://app.globus.org/file-manager?origin_id=68c86914-a133-4e16-963d-028cc5f60cea&origin_path=%2F
